set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS18} [get_ports a]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVCMOS18} [get_ports b]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS18} [get_ports d0]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS18} [get_ports d1]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS18} [get_ports d2]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS18} [get_ports d3]