set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS18} [get_ports f]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVCMOS18} [get_ports a]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS18} [get_ports b]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS18} [get_ports w]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS18} [get_ports x]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS18} [get_ports y]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS18} [get_ports z]
