set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS18} [get_ports d0]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVCMOS18} [get_ports d1]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS18} [get_ports d2]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS18} [get_ports d3]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS18} [get_ports e0]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS18} [get_ports e1]