set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS18} [get_ports s0]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVCMOS18} [get_ports s1]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS18} [get_ports a]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS18} [get_ports b]
set_property -dict {PACKAGE_PIN K6 IOSTANDARD LVCMOS18} [get_ports c]
set_property -dict {PACKAGE_PIN J6 IOSTANDARD LVCMOS18} [get_ports d]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS18} [get_ports y]
