set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]
set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVCMOS18} [get_ports clk]
set_property -dict {PACKAGE_PIN E21 IOSTANDARD LVCMOS18} [get_ports rst]
set_property -dict {PACKAGE_PIN D21 IOSTANDARD LVCMOS18} [get_ports x]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS18} [get_ports seq[3]]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS18} [get_ports seq[2]]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS18} [get_ports seq[1]]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS18} [get_ports seq[0]]
set_property -dict {PACKAGE_PIN W12 IOSTANDARD LVCMOS18} [get_ports z]
